export const Details = [
  {
    RID: "DEHDITbc51ed",
    PgName: "Maya PG",
    Address:
      "C33J+88Q Maya PG, Bagryal, village, near DIT college, opposite Mega county, Salan Gaon, Bhagwant Pur, Dehradun",
    Landmark: "Near DIT University Gate",
    PgType: "Boys",
    imgPaths: [
      "./images/PgInfoImgs/DEHDITbc51ed/mainImg.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img1.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img2.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img3.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img4.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img4.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img4.jpg",
      "./images/PgInfoImgs/DEHDITbc51ed/img4.jpg",
    ],
    Rooms: [
      {
        RoomNo: "101",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Single",
        Rent: "8000",
        AvailFrom: "2025-07-01",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "102",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Double",
        Rent: "7000",
        AvailFrom: 0,
        Rating: 3.8,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/102/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/102/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/102/img2.jpg",
        ],
      },
      {
        RoomNo: "103",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Triple",
        Rent: "4900",
        AvailFrom: "2025-07-05",
        Rating: 4.9,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/103/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/103/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/103/img2.jpg",
        ],
      },

      {
        RoomNo: "104",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Double",
        Rent: "7500",
        AvailFrom: 0,
        Rating: 3.8,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/104/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/104/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/104/img2.jpg",
        ],
      },
      {
        RoomNo: "105",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Single",
        Rent: "7000",
        AvailFrom: "2025-07-10",
        Rating: 3.9,
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/105/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/105/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/105/img2.jpg",
        ],
      },
      {
        RoomNo: "106",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Triple",
        Rent: "4500",
        AvailFrom: "2025-07-05",
        Rating: 3.2,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/106/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/106/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/106/img2.jpg",
        ],
      },
      {
        RoomNo: "107",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Single",
        Rent: "7000",
        AvailFrom: 0,
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/107/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/107/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/107/img2.jpg",
        ],
      },
      {
        RoomNo: "108",
        desc: "This is a very good room , it has the following features and the locality is alos goodina pedre tu cianta voa casano la punita me casana This is a very good room , it has the following features and the locality is alos goodina pedre tu",
        Type: "Double",
        Rent: "6500",
        AvailFrom: "2025-07-05",
        Rating: 4.2,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/108/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/108/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/108/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8000",
  },
  {
    RID: "NOISEC7eb4aa",
    PgName: "Sector 62 Homestay",
    Address:
      "B12K+22P Sunrise PG, Sector 62, block A, near City Center, opposite Green Park, Noida, Uttar Pradesh",
    Landmark: "Near Fortis Hospital",
    PgType: "Co-ed",
    imgPaths: [
      "./images/PgInfoImgs/NOISEC7eb4aa/mainImg.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img1.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img2.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img3.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img4.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img4.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img4.jpg",
      "./images/PgInfoImgs/NOISEC7eb4aa/img4.jpg",
    ],
    Rooms: [
      {
        RoomNo: "201",
        Type: "Double",
        Rent: "6500",
        AvailFrom: "2025-07-03",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "202",
        Type: "Triple",
        Rent: "6000",
        AvailFrom: "2025-07-08",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "203",
        Type: "Single",
        Rent: "7500",
        AvailFrom: "2025-07-12",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "7000",
  },
  {
    RID: "GURMGRc68efd",
    PgName: "MG Comfort PG",
    Address:
      "F45J+19Q Comfort PG, Sikanderpur, village, near MG Road Metro, opposite DLF City Court, Gurgaon, Haryana",
    Landmark: "Opposite MGF Mall",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "B1",
        Type: "Single",
        Rent: "9000",
        AvailFrom: "2025-07-15",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "B2",
        Type: "Double",
        Rent: "8500",
        AvailFrom: "2025-07-20",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "B3",
        Type: "Triple",
        Rent: "8000",
        AvailFrom: "2025-07-25",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "9000",
  },
  {
    RID: "PUNCENadd957",
    PgName: "Pune Central Studio",
    Address:
      "D21M+77R Urban PG, Shivaji Nagar, lane 5, near Pune Central Mall, opposite City Pride, Pune, Maharashtra",
    Landmark: "Near Shivaji Nagar",
    PgType: "Studio",
    Rooms: [
      {
        RoomNo: "S1",
        Type: "Single",
        Rent: "12000",
        AvailFrom: "2025-07-01",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "S2",
        Type: "Studio",
        Rent: "12500",
        AvailFrom: "2025-07-10",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "S3",
        Type: "Studio",
        Rent: "13000",
        AvailFrom: "2025-07-15",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "12000",
  },
  {
    RID: "GURDLF10e38d",
    PgName: "DLF Sharing PG",
    Address:
      "E33N+55S DLF PG, Phase 3, street 10, near Cyber Hub, opposite DLF Square, Gurgaon, Haryana",
    Landmark: "Near Cyber Hub",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "G1",
        Type: "Double",
        Rent: "7000",
        AvailFrom: "2025-07-02",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "G2",
        Type: "Triple",
        Rent: "6500",
        AvailFrom: "2025-07-10",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "G3",
        Type: "Double",
        Rent: "7000",
        AvailFrom: "2025-07-07",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "7000",
  },
  {
    RID: "DELSAKa4aaf9",
    PgName: "Saket Stay PG",
    Address:
      "A11L+88V Saket PG, H-Block, near PVR Saket, opposite Select Citywalk, Saket, New Delhi",
    Landmark: "Near PVR Saket",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "SK1",
        Type: "Single",
        Rent: "10000",
        AvailFrom: "2025-07-04",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SK2",
        Type: "Double",
        Rent: "9500",
        AvailFrom: "2025-07-08",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SK3",
        Type: "Triple",
        Rent: "9000",
        AvailFrom: "2025-07-12",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "10000",
  },
  {
    RID: "BANCENfa17ea",
    PgName: "Bangalore Modern PG",
    Address:
      "G12P+33K Modern PG, 4th Main Road, Indiranagar, near Metro Station, opposite BDA Complex, Bangalore, Karnataka",
    Landmark: "Near Metro Station",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "BLR1",
        Type: "Single",
        Rent: "11000",
        AvailFrom: "2025-07-06",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "BLR2",
        Type: "Double",
        Rent: "10000",
        AvailFrom: "2025-07-15",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "BLR3",
        Type: "Triple",
        Rent: "9500",
        AvailFrom: "2025-07-18",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "11000",
  },
  {
    RID: "DEHCIT80e5d6",
    PgName: "City PG Dehradun",
    Address:
      "C44J+99Q City PG, Clement Town, opposite Graphic Era Hill University, Dehradun, Uttarakhand",
    Landmark: "Opposite Pacific Mall",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "CT1",
        Type: "Single",
        Rent: "6000",
        AvailFrom: "2025-07-03",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "CT2",
        Type: "Double",
        Rent: "5800",
        AvailFrom: "2025-07-06",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "CT3",
        Type: "Triple",
        Rent: "5500",
        AvailFrom: "2025-07-09",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "6000",
  },
  {
    RID: "DELROHebe203",
    PgName: "Rohini Budget PG",
    Address:
      "B23K+12L Budget PG, Sector 7, near Rohini West Metro, opposite City Park, Rohini, Delhi",
    Landmark: "Near Rohini West Metro",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "R1",
        Type: "Triple",
        Rent: "5500",
        AvailFrom: "2025-07-10",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "R2",
        Type: "Double",
        Rent: "5800",
        AvailFrom: "2025-07-14",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "R3",
        Type: "Single",
        Rent: "6000",
        AvailFrom: "2025-07-20",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "5500",
  },
  {
    RID: "DELRAJ49ba4f",
    PgName: "Rajiv Chowk Stay",
    Address:
      "D55M+44P Rajiv PG, Connaught Place, near Metro Gate No. 5, opposite Palika Bazar, New Delhi",
    Landmark: "Near Metro Gate No. 5",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "RC1",
        Type: "Single",
        Rent: "9500",
        AvailFrom: "2025-07-07",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "RC2",
        Type: "Double",
        Rent: "9000",
        AvailFrom: "2025-07-13",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "RC3",
        Type: "Triple",
        Rent: "8700",
        AvailFrom: "2025-07-17",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "9500",
  },
  {
    RID: "GURSECb5b54d",
    PgName: "Sector 45 Residency",
    Address:
      "F12N+67Q Residency PG, Sector 45, block B, near Huda City Centre, opposite Amity School, Gurgaon, Haryana",
    Landmark: "Near Huda City Centre",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "101",
        Type: "Single",
        Rent: "8500",
        AvailFrom: "2025-07-01",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "102",
        Type: "Double",
        Rent: "7500",
        AvailFrom: "2025-07-07",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "103",
        Type: "Triple",
        Rent: "7000",
        AvailFrom: "2025-07-15",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8500",
  },
  {
    RID: "DELJAN04b237",
    PgName: "Janakpuri Comfort PG",
    Address:
      "A23L+55V Comfort PG, C-Block, near Janakpuri West Metro, opposite District Park, Janakpuri, New Delhi",
    Landmark: "Near Janakpuri West Metro",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "J1",
        Type: "Single",
        Rent: "9000",
        AvailFrom: "2025-07-03",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "J2",
        Type: "Double",
        Rent: "8500",
        AvailFrom: "2025-07-09",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "J3",
        Type: "Triple",
        Rent: "8000",
        AvailFrom: "2025-07-20",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "9000",
  },
  {
    RID: "NOINOH2761fd",
    PgName: "Noida House PG",
    Address:
      "B34K+88P House PG, Sector 50, block D, near Sector 50 Market, opposite City Plaza, Noida, Uttar Pradesh",
    Landmark: "Near Sector 50 Market",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "NH1",
        Type: "Single",
        Rent: "7000",
        AvailFrom: "2025-07-02",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "NH2",
        Type: "Double",
        Rent: "6500",
        AvailFrom: "2025-07-05",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "NH3",
        Type: "Triple",
        Rent: "6000",
        AvailFrom: "2025-07-10",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "7000",
  },
  {
    RID: "BANELE18eac4",
    PgName: "Electronic City PG",
    Address:
      "G56P+21K E-City PG, Phase 1, near Infosys Campus, opposite Tech Park, Electronic City, Bangalore, Karnataka",
    Landmark: "Beside Infosys Campus",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "EC1",
        Type: "Single",
        Rent: "8000",
        AvailFrom: "2025-07-06",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "EC2",
        Type: "Double",
        Rent: "7500",
        AvailFrom: "2025-07-12",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "EC3",
        Type: "Triple",
        Rent: "7000",
        AvailFrom: "2025-07-17",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8000",
  },
  {
    RID: "DEHPRT6d7391",
    PgName: "Prince Town PG",
    Address:
      "C77J+55Q Prince PG, Prince Chowk, near Railway Station, opposite Hotel Grand, Dehradun, Uttarakhand",
    Landmark: "Near Railway Station",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "PT1",
        Type: "Single",
        Rent: "6200",
        AvailFrom: "2025-07-04",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "PT2",
        Type: "Double",
        Rent: "5800",
        AvailFrom: "2025-07-08",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "PT3",
        Type: "Triple",
        Rent: "5500",
        AvailFrom: "2025-07-14",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "6200",
  },
  {
    RID: "PUNKOT358ea0",
    PgName: "Kothrud Elite PG",
    Address:
      "D56M+33R Elite PG, Kothrud Main Road, near MIT College, opposite City Hospital, Pune, Maharashtra",
    Landmark: "Near MIT College",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "KT1",
        Type: "Single",
        Rent: "9000",
        AvailFrom: "2025-07-05",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "KT2",
        Type: "Double",
        Rent: "8500",
        AvailFrom: "2025-07-11",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "KT3",
        Type: "Triple",
        Rent: "8000",
        AvailFrom: "2025-07-18",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "9000",
  },
  {
    RID: "BANGODd3f94e",
    PgName: "Gopal Krishna PG",
    Address:
      "G78P+44K Krishna PG, Rajajinagar, near Orion Mall, opposite Metro Station, Bangalore, Karnataka",
    Landmark: "Near Orion Mall",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "GK1",
        Type: "Single",
        Rent: "8700",
        AvailFrom: "2025-07-02",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "GK2",
        Type: "Double",
        Rent: "8200",
        AvailFrom: "2025-07-09",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "GK3",
        Type: "Triple",
        Rent: "7700",
        AvailFrom: "2025-07-16",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8700",
  },
  {
    RID: "DEHRAJ1f123a",
    PgName: "Rajpur Road Stays",
    Address:
      "C88J+77Q Rajpur PG, Rajpur Road, near Pacific Hotel, opposite Rajpur Market, Dehradun, Uttarakhand",
    Landmark: "Opposite Pacific Hotel",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "RR1",
        Type: "Single",
        Rent: "5800",
        AvailFrom: "2025-07-01",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "RR2",
        Type: "Double",
        Rent: "5500",
        AvailFrom: "2025-07-07",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "RR3",
        Type: "Triple",
        Rent: "5000",
        AvailFrom: "2025-07-13",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "5800",
  },
  {
    RID: "NOISECb46ac9",
    PgName: "Sec 18 Noida PG",
    Address:
      "B56K+99P Sec 18 PG, Sector 18, near Atta Market, opposite Wave Mall, Noida, Uttar Pradesh",
    Landmark: "Near Atta Market",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "S18-1",
        Type: "Single",
        Rent: "9500",
        AvailFrom: "2025-07-06",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "S18-2",
        Type: "Double",
        Rent: "9000",
        AvailFrom: "2025-07-12",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "S18-3",
        Type: "Triple",
        Rent: "8700",
        AvailFrom: "2025-07-19",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "9500",
  },
  {
    RID: "DELUTT3db2ee",
    PgName: "Uttam Nagar Gents PG",
    Address:
      "A44L+11V Gents PG, Uttam Nagar East, near Metro Pillar 689, opposite City Park, New Delhi",
    Landmark: "Near Metro Pillar 689",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "UN1",
        Type: "Single",
        Rent: "6000",
        AvailFrom: "2025-07-09",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "UN2",
        Type: "Double",
        Rent: "5500",
        AvailFrom: "2025-07-14",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "UN3",
        Type: "Triple",
        Rent: "5000",
        AvailFrom: "2025-07-21",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "6000",
  },
  {
    RID: "GURDLFa12cf0",
    PgName: "DLF Phase 3 PG",
    Address:
      "E22N+88S DLF PG, U Block, DLF Phase 3, near Cyber City, opposite DLF Square, Gurgaon, Haryana",
    Landmark: "Near Cyber City",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "DLF1",
        Type: "Single",
        Rent: "10000",
        AvailFrom: "2025-07-02",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "DLF2",
        Type: "Double",
        Rent: "9500",
        AvailFrom: "2025-07-10",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "DLF3",
        Type: "Triple",
        Rent: "9000",
        AvailFrom: "2025-07-18",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "10000",
  },
  {
    RID: "DEHISBr324a1",
    PgName: "ISBT Area PG",
    Address:
      "C77J+55Q ISBT PG, ISBT Road, near Bus Terminal, opposite City Bus Stand, Dehradun, Uttarakhand",
    Landmark: "Near Bus Terminal",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "IS1",
        Type: "Single",
        Rent: "6000",
        AvailFrom: "2025-07-05",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "IS2",
        Type: "Double",
        Rent: "5600",
        AvailFrom: "2025-07-12",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "IS3",
        Type: "Triple",
        Rent: "5200",
        AvailFrom: "2025-07-19",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "6000",
  },
  {
    RID: "DELNAS88c3ab",
    PgName: "Nash Market PG",
    Address:
      "A99L+33V Nash PG, Nash Market, near Army Base Hospital, opposite Cantt Park, Delhi Cantt, New Delhi",
    Landmark: "Near Army Base Hospital",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "NS1",
        Type: "Single",
        Rent: "7200",
        AvailFrom: "2025-07-01",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "NS2",
        Type: "Double",
        Rent: "6700",
        AvailFrom: "2025-07-08",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "NS3",
        Type: "Triple",
        Rent: "6200",
        AvailFrom: "2025-07-15",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "7200",
  },
  {
    RID: "PUNSHIb7c865",
    PgName: "Shivaji Nagar PG",
    Address:
      "D88M+44R Shivaji PG, Lane 3, Shivaji Nagar, near Shivajinagar Bus Stand, opposite City Library, Pune, Maharashtra",
    Landmark: "Near Shivajinagar Bus Stand",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "SN1",
        Type: "Single",
        Rent: "8700",
        AvailFrom: "2025-07-04",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SN2",
        Type: "Double",
        Rent: "8300",
        AvailFrom: "2025-07-11",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SN3",
        Type: "Triple",
        Rent: "7900",
        AvailFrom: "2025-07-18",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8700",
  },
  {
    RID: "BANMAR0a97ae",
    PgName: "Marathahalli Comfort PG",
    Address:
      "G33P+22K Comfort PG, Outer Ring Road, Marathahalli, near Innovative Multiplex, opposite Tech Park, Bangalore, Karnataka",
    Landmark: "Opposite Innovative Multiplex",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "MH1",
        Type: "Single",
        Rent: "9100",
        AvailFrom: "2025-07-03",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "MH2",
        Type: "Double",
        Rent: "8700",
        AvailFrom: "2025-07-10",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "MH3",
        Type: "Triple",
        Rent: "8300",
        AvailFrom: "2025-07-17",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "9100",
  },
  {
    RID: "NOISEC4a2f69",
    PgName: "Noida Sector 62 PG",
    Address:
      "B12K+22P Sector 62 PG, B-15, Sector 62, near Jaypee Institute, opposite City Center, Noida, Uttar Pradesh",
    Landmark: "Near Jaypee Institute",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "N62-1",
        Type: "Single",
        Rent: "7800",
        AvailFrom: "2025-07-05",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "N62-2",
        Type: "Double",
        Rent: "7400",
        AvailFrom: "2025-07-13",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "N62-3",
        Type: "Triple",
        Rent: "7000",
        AvailFrom: "2025-07-20",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "7800",
  },
  {
    RID: "BANGOTbcfa65",
    PgName: "Gottigere PG",
    Address:
      "G99P+77K Gottigere PG, Bannerghatta Road, near NICE Road Junction, opposite City Mall, Bangalore, Karnataka",
    Landmark: "Near NICE Road Junction",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "GT1",
        Type: "Single",
        Rent: "8600",
        AvailFrom: "2025-07-07",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "GT2",
        Type: "Double",
        Rent: "8200",
        AvailFrom: "2025-07-14",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "GT3",
        Type: "Triple",
        Rent: "7800",
        AvailFrom: "2025-07-21",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8600",
  },
  {
    RID: "DEHSAR203a0d",
    PgName: "Saharanpur Road PG",
    Address:
      "C55J+66Q Saharanpur PG, Saharanpur Road, near Coca Cola Factory, opposite City Hospital, Dehradun, Uttarakhand",
    Landmark: "Opposite Coca Cola Factory",
    PgType: "Girls",
    Rooms: [
      {
        RoomNo: "SR1",
        Type: "Single",
        Rent: "6000",
        AvailFrom: "2025-07-06",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SR2",
        Type: "Double",
        Rent: "5500",
        AvailFrom: "2025-07-12",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SR3",
        Type: "Triple",
        Rent: "5100",
        AvailFrom: "2025-07-19",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "6000",
  },
  {
    RID: "DEHPAT9f9431",
    PgName: "Patel Nagar PG",
    Address:
      "C22J+33Q Patel PG, Patel Nagar, near Hotel Ajanta, opposite City Market, Dehradun, Uttarakhand",
    Landmark: "Near Hotel Ajanta",
    PgType: "Boys",
    Rooms: [
      {
        RoomNo: "PN1",
        Type: "Single",
        Rent: "5700",
        AvailFrom: "2025-07-04",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "PN2",
        Type: "Double",
        Rent: "5400",
        AvailFrom: "2025-07-11",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "PN3",
        Type: "Triple",
        Rent: "5000",
        AvailFrom: "2025-07-17",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "5700",
  },
  {
    RID: "PUNSAD890e07",
    PgName: "Sadashiv Peth Stay",
    Address:
      "D44M+11R Sadashiv PG, Sadashiv Peth, near SP College, opposite City Library, Pune, Maharashtra",
    Landmark: "Near SP College",
    PgType: "Co-ed",
    Rooms: [
      {
        RoomNo: "SP1",
        Type: "Single",
        Rent: "8800",
        AvailFrom: "2025-07-09",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SP2",
        Type: "Double",
        Rent: "8400",
        AvailFrom: "2025-07-16",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
      {
        RoomNo: "SP3",
        Type: "Triple",
        Rent: "8000",
        AvailFrom: "2025-07-23",
        Rating: 4.1,
        features: [
          "Air conditioned",
          "Attached Bathroom",
          "Study table and chair",
          "2 charging points",
          "Balcony/Window view",
        ],
        images: [
          "/images/PgInfoImgs/DEHDITbc51ed/101/mainImg.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img1.jpg",
          "/images/PgInfoImgs/DEHDITbc51ed/101/img2.jpg",
        ],
      },
    ],
    SecurityDeposit: "8800",
  },
];
