export const PGReviews = [
  // DEHDITbc51ed
  {
    RID: "DEHDITbc51ed",
    review:
      "I couldn’t have asked for a better place to stay during my internship. The rooms are spacious, and the beds are super comfy. The food is just like home — healthy and not too spicy. The staff is polite, and the best part is that everything is cleaned regularly. There's even a small balcony where I used to chill in the evenings. Highly recommended for working professionals!",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "ritik_dit22",
    date: "2025-06-06",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "The crowd here is amazing — mostly students from nearby colleges, so it has a very chill and productive vibe. The Wi-Fi is strong, and the study area is quiet and perfect for group studies. The food is okay, could be improved slightly. Overall, it's a solid PG with good vibes and great facilities.",
    finalRating: 3.9,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "muskan_singh",
    date: "2025-04-25",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "The place is affordable and close to the metro, which was a big plus. The rooms are average-sized, but the walls are a bit thin, so you can hear noise from next door. Food is fine for the price, but I’d recommend eating out sometimes. Good for short stays or those on a tight budget.",
    finalRating: 3.1,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "adityasharma01",
    date: "2025-05-03",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "One of the safest girls’ PGs I’ve stayed in. 24/7 female staff, CCTV surveillance, and biometric entry made us feel secure. The food was always fresh, and they even had special weekend meals. Rooms are cozy with good ventilation. I would totally recommend it to any girl moving to Gurgaon for studies or work.",
    finalRating: 2.9,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "kritika_13",
    date: "2025-04-30",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "This place has the vibe of a serviced apartment. Interiors are modern, with a mini fridge, attached bathroom, and AC in every room. The common area is like a co-living lounge with bean bags, Netflix, and a mini library. Totally worth the rent if you want comfort + community.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "yash_t",
    date: "2025-05-15",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "Honestly, I expected more based on the pictures. The rooms were smaller than shown, and the Wi-Fi barely worked during peak hours. The food was repetitive, and once the geyser didn’t work for 2 days. The only plus is its walking distance from college. Needs serious maintenance.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "neha.m",
    date: "2025-04-17",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "If you're a serious student, this is the PG for you. Super silent, Wi-Fi doesn’t lag during Zoom classes or online tests. Food is healthy, less oily. They even provide boiled eggs and fruits for breakfast. A great place for focused preparation. Would’ve been 5 stars if they had a small gym.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "shivam_07",
    date: "2025-05-05",
  },
  {
    RID: "DEHDITbc51ed",
    review:
      "I stayed here for a month while shifting jobs, and I was really impressed. The check-in process was smooth, no deposit needed, and they provided fresh bedding and daily cleaning. Food was simple but tasty. Ideal for short-term working professionals or interns.",
    finalRating: 4.3,
    communityAndEnvironmentRating: 4.5,
    valueForMoneyRating: 4.2,
    locationRating: 4.7,
    foodRating: 3.9,
    landlordRating: 4.3,
    username: "priya_dit",
    date: "2025-05-01",
  },

  // NOISEC7eb4aa
  {
    RID: "NOISEC7eb4aa",
    review:
      "I loved the peaceful environment here. The interiors are minimal and soothing — very different from the usual cramped PGs. Wi-Fi, laundry, and 24/7 water supply — all top-notch. Also, the rooftop common area is the best part — you can study, chill, or do yoga with a view.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "rohan_techie",
    date: "2025-05-10",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Facilities are excellent — food variety, regular cleaning, and even Netflix in the common area. But honestly, the rent feels a bit high compared to similar PGs nearby. If you don’t mind paying a premium for good service and convenience, this might be the one for you.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "ayushi_noida",
    date: "2025-05-06",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Security is tight here. Biometric entry and CCTV everywhere. I felt very safe.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "ankur_123",
    date: "2025-05-02",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Food quality is great on most days. Sometimes breakfast is a bit cold, but overall fine.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "megha_vibes",
    date: "2025-04-28",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "My room had a private balcony — loved having coffee there in the evenings.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "shrey27",
    date: "2025-05-12",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Only downside: the Wi-Fi occasionally lags during office hours. Could be improved.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "deepak_j",
    date: "2025-04-26",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "They even have a game room and rooftop lounge. Honestly felt more like a hostel than a PG!",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "riya_b",
    date: "2025-05-08",
  },
  {
    RID: "NOISEC7eb4aa",
    review:
      "Clean washrooms, 24/7 hot water, and cooperative staff. Smooth experience overall.",
    finalRating: 4.6,
    communityAndEnvironmentRating: 4.8,
    valueForMoneyRating: 4.4,
    locationRating: 4.9,
    foodRating: 4.2,
    landlordRating: 4.7,
    username: "anmol.dev",
    date: "2025-05-04",
  },

  // GURMG c68efd
  {
    RID: "GURMG c68efd",
    review:
      "Luxurious PG setup. Feels like a co-living space more than a traditional PG.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "harshit_mg",
    date: "2025-05-01",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Great for working professionals. Walking distance to metro and malls like Sahara & MGF.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "isha_k",
    date: "2025-05-13",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Bit noisy outside due to traffic, but inside the PG it’s calm and soundproof.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "varun.g",
    date: "2025-04-30",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Manager is responsive to complaints and maintenance is quick. Thumbs up.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "nandini.dev",
    date: "2025-04-22",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Room interiors are really nice — wooden floor, good lighting, and comfy beds.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "rahulmg",
    date: "2025-05-06",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Shared room but partitioned smartly. Felt like I had my own private space.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "deepa_kr",
    date: "2025-05-09",
  },
  {
    RID: "GURMG c68efd",
    review:
      "Food is outsourced, so it’s restaurant-quality most of the time. No complaints.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "amit.1999",
    date: "2025-05-03",
  },
  {
    RID: "GURMG c68efd",
    review:
      "I’ve changed 3 PGs in Gurgaon — this one was the best balance of price and quality.",
    finalRating: 4.7,
    communityAndEnvironmentRating: 4.6,
    valueForMoneyRating: 4.5,
    locationRating: 4.8,
    foodRating: 4.3,
    landlordRating: 4.9,
    username: "rashika_s",
    date: "2025-05-14",
  },

  // PUNCENadd957
  {
    RID: "PUNCENadd957",
    review:
      "Super clean PG. They clean rooms and common areas daily without fail.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "jatin",
  },
  {
    RID: "PUNCENadd957",
    review:
      "The best part is the location — right in the heart of the city. Everything’s nearby.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "shraddha.23",
    date: "2025-04-25",
  },
  {
    RID: "PUNCENadd957",
    review: "Food is simple but hygienic. Loved the rajma-chawal days!",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "sumit17",
    date: "2025-04-27",
  },
  {
    RID: "PUNCENadd957",
    review: "Warden aunty is sweet and always ready to help. Feels homely.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "ananya_v",
    date: "2025-05-02",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Wi-Fi is strong, even during peak hours. No buffering during Netflix binges!",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "ravi.ch",
    date: "2025-04-29",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Perfect place for students from PU and nearby colleges. Very student-friendly.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "neeraj_pu",
    date: "2025-05-04",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Rooms are decent in size. Mattress quality could be better, though.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "komal_01",
    date: "2025-04-26",
  },
  {
    RID: "PUNCENadd957",
    review:
      "Affordable, quiet, and well-maintained. I’ll recommend it to any newcomer in Chandigarh.",
    finalRating: 4.5,
    communityAndEnvironmentRating: 4.7,
    valueForMoneyRating: 4.6,
    locationRating: 4.6,
    foodRating: 4.1,
    landlordRating: 4.4,
    username: "siddharth.chd",
    date: "2025-05-07",
  },
];
