export const cityAreaMap = {
  "201301": { 
    city: "Noida / Greater Noida",
    areas: [
      { code: "SEC", name: "Sector 62" },
      { code: "S18", name: "Sector 18" },
      { code: "S82", name: "Sector 82/83" },
      { code: "S12", name: "Sector 125/126" },
      { code: "S13", name: "Sector 137/140" },
      { code: "S15", name: "Sector 150" },
      { code: "S44", name: "Sector 44/45" },
      { code: "KPK", name: "Knowledge Park I & II" },
      { code: "ECO", name: "Ecotech" },
      { code: "ALP", name: "Alpha I & II" },
      { code: "BET", name: "Beta I & II" },
      { code: "GNW", name: "Greater Noida West" },
      { code: "PAR", name: "Pari Chowk / Yatharth area" },
      { code: "DAD", name: "Dadri Road" },
      { code: "FIL", name: "Film City Noida" },
    ],
  },
  "122001": {
    city: "Gurgaon",
    areas: [
      { code: "DLF", name: "Cyber City / DLF Ph 1 to 5" },
      { code: "MGR", name: "MG Road / Golf Course Road" },
      { code: "SOH", name: "Sohna Road" },
      { code: "S14", name: "Sector 14/15/29" },
      { code: "S44", name: "Sector 44/45" },
      { code: "UDY", name: "Udyog Vihar" },
      { code: "S56", name: "Sector 56/57" },
      { code: "S62", name: "Sector 62" },
      { code: "PAL", name: "Palam Vihar" },
      { code: "P56", name: "DLF Phase 5/6" },
      { code: "GCE", name: "Golf Course Extension Road" },
      { code: "S49", name: "Sector 49/50" },
      { code: "S23", name: "Sector 23/24" },
      { code: "JHA", name: "Jharsa / Hansali" },
      { code: "PAT", name: "Pataudi Road" },
    ],
  },
  "248003": {
    city: "Dehradun",
    areas: [
      { code: "DIT", name: "DIT University area" },
      { code: "GRA", name: "Graphic Era University zone" },
      { code: "DOO", name: "Doon University zone" },
      { code: "IUE", name: "IEHMITS / UTU corridor" },
      { code: "ISB", name: "ISBT" },
      { code: "PRE", name: "Prem Nagar" },
      { code: "RAJ", name: "Rajpur Road" },
      { code: "BAL", name: "Ballupur / Gandhi Colony" },
      { code: "CLO", name: "Clock Tower" },
      { code: "PAT", name: "Patel Nagar / Sahastradhara Road" },
      { code: "JAK", name: "Jakhan area" },
      { code: "ECR", name: "EC Road zone" },
      { code: "KAU", name: "Kaulagarh Road" },
      { code: "MAJ", name: "Majra area" },
      { code: "CLE", name: "Clement Town" },
    ],
  },
  "110001": {
    city: "Delhi",
    areas: [
      { code: "KAM", name: "North Campus / Kamla Nagar (DU)" },
      { code: "HUD", name: "Hudson Lane" },
      { code: "KAR", name: "Karol Bagh" },
      { code: "JAN", name: "Janakpuri" },
      { code: "LAJ", name: "Lajpat Nagar" },
      { code: "LAX", name: "Laxmi Nagar" },
      { code: "PIT", name: "Pitampura" },
      { code: "ROH", name: "Rohini" },
      { code: "SAK", name: "Saket" },
      { code: "HAU", name: "Hauz Khas" },
      { code: "RAJ", name: "Rajiv Chowk / Connaught Place" },
      { code: "SUT", name: "South Extension / Greater Kailash" },
      { code: "VAS", name: "Vasant Kunj" },
      { code: "ANA", name: "Anand Vihar" },
      { code: "DWA", name: "Dwarka" },
    ],
  },
  "201002": {
    city: "Ghaziabad",
    areas: [
      { code: "RAJ", name: "Raj Nagar Extension" },
      { code: "KAV", name: "Kavi Nagar" },
      { code: "PAT", name: "Patel Nagar" },
      { code: "SHA", name: "Shastri Nagar" },
      { code: "VIJ", name: "Vijay Nagar" },
      { code: "IND", name: "Indirapuram" },
      { code: "KAU", name: "Kaushambi" },
      { code: "VAI", name: "Vaishali" },
      { code: "MOH", name: "Mohan Nagar" },
      { code: "LAJ", name: "Lajpat Nagar Ghaziabad" },
      { code: "NEH", name: "Nehru Nagar" },
      { code: "PRA", name: "Pratap Vihar" },
      { code: "GOV", name: "Govindpuram" },
      { code: "SAH", name: "Sahibabad" },
      { code: "CRO", name: "Crossings Republik" },
    ],
  },
  "121001": {
    city: "Faridabad",
    areas: [
      { code: "S15", name: "Sector 15" },
      { code: "S16", name: "Sector 16" },
      { code: "S21", name: "Sector 21C" },
      { code: "S28", name: "Sector 28" },
      { code: "S37", name: "Sector 37" },
      { code: "S46", name: "Sector 46" },
      { code: "NIT", name: "NIT 1–5" },
      { code: "AJR", name: "Ajronda / Old Faridabad" },
      { code: "BAL", name: "Ballabhgarh" },
      { code: "NEE", name: "Neelam Chowk" },
      { code: "GRE", name: "Greenfield Colony" },
      { code: "CHA", name: "Charmwood Village" },
      { code: "BPT", name: "BPTP area" },
      { code: "SUR", name: "Surajkund" },
      { code: "S09", name: "Sector 9" },
    ],
  },
  "247667": {
    city: "Roorkee",
    areas: [
      { code: "IIT", name: "IIT Roorkee Campus & Adjacent Areas" },
      { code: "SOL", name: "Solani Kunj" },
      { code: "CIV", name: "Civil Lines" },
      { code: "GAN", name: "Ganeshpur" },
      { code: "RAM", name: "Ramnagar" },
      { code: "PRE", name: "Prem Nagar" },
      { code: "ANA", name: "Anaj Mandi" },
      { code: "RAI", name: "Railway Road" },
      { code: "PIR", name: "Piran Kaliyar Road" },
      { code: "SHI", name: "Shivalik Nagar" },
      { code: "OLD", name: "Old Roorkee Town" },
      { code: "COE", name: "COER College Area" },
      { code: "QUA", name: "Quantum University Zone" },
      { code: "MOD", name: "Modipuram" },
      { code: "HAR", name: "Haridwar Road" },
    ],
  },
  "249401": {
    city: "Haridwar",
    areas: [
      { code: "GUR", name: "Gurukula Kangri University Area" },
      { code: "BAH", name: "Bahadrabad" },
      { code: "SHI", name: "Shivalik Nagar" },
      { code: "JWA", name: "Jwalapur" },
      { code: "SID", name: "SIDCUL Industrial Area" },
      { code: "BHU", name: "Bhupatwala" },
      { code: "RAN", name: "Ranipur More" },
      { code: "HKP", name: "Har-ki-Pauri / Central" },
      { code: "DEV", name: "Devpura" },
      { code: "KAN", name: "Kankhal" },
      { code: "BHE", name: "BHEL Township" },
      { code: "ROS", name: "Roshnabad" },
      { code: "MAY", name: "Mayapur" },
      { code: "BMM", name: "Bharat Mata Mandir Zone" },
      { code: "IND", name: "Industrial Estate Area" },
    ],
  },
};

